modLoader="lowcodefml"
loaderVersion="[1,)"
license="LicenseRef-All-Rights-Reserved"
showAsResourcePack=false
showAsDataPack=false
issueTrackerURL="https://github.com/magmamir/Deformation-Dimension/issues"


[[mods]]
  modId="deformation_dimension"
  namespace="mmdp.deformation"
  version="1.21.4-1.0.2"
  displayName="Deformation Dimension"
  updateJSONURL="https://api.modrinth.com/updates/deformation-dimension/forge_updates.json?neoforge=include"
  modUrl="https://modrinth.com/datapack/deformation-dimension"
  displayURL="https://modrinth.com/datapack/deformation-dimension"
  logoFile="pack.png"
  logoBlur=false
  authors="magmamir, _Sasha_Lapa_"
  credits='''
  
  magmamir — Coder
  _Sasha_Lapa_ — Artist
  good7777865 — Translator (ko_kr)
  Atten007 — Translator (de_de)'''
  
  description='''
Nerfs elytra by adding an entirely new dungeon-like dimension you need to complete to obtain one.

REQUIREMENTS:
 - Minecraft 1.21.4
 - [ETF] Entity Texture Features
 - [EMF] Entity Model Features
 - Polytone
 - MoreMcmeta (OPTIONAL)
'''


[[dependencies.deformation_dimension]]
  modId = "minecraft"
  type = "required"
  versionRange = "[1.21.4]"
  ordering = "NONE"
  side = "BOTH"

[[dependencies.deformation_dimension]]
  modId = "entity_texture_features"
  type = "required"
  versionRange = "[6.2.9,)"
  ordering = "NONE"
  side = "CLIENT"
  referralUrl="https://modrinth.com/mod/entitytexturefeatures"

[[dependencies.deformation_dimension]]
  modId = "entity_model_features"
  type = "required"
  versionRange = "[2.4.0,)"
  ordering = "NONE"
  side = "CLIENT"
  referralUrl="https://modrinth.com/mod/entity-model-features"
   
[[dependencies.deformation_dimension]]
  modId = "polytone"
  type = "required"
  versionRange = "[1.21.4-3.2.7,)"
  ordering = "NONE"
  side = "CLIENT"
  referralUrl="https://modrinth.com/mod/polytone"
  
[[dependencies.deformation_dimension]]
  modId = "moremcmeta"
  type = "optional"
  versionRange = ""
  ordering = "NONE"
  side = "CLIENT"
  referralUrl="https://modrinth.com/mod/moremcmeta"